SQUARE_SIZE = 100
SIDEBAR_WIDTH = 200
SCREEN_SIZE = (SQUARE_SIZE * 8 + SIDEBAR_WIDTH, SQUARE_SIZE * 8)

X_UPPER_BOUNDARY = 700
Y_UPPER_BOUNDARY = 700
X_LOWER_BOUNDARY = 0
Y_LOWER_BOUNDARY = 0

FPS = 60
